version: '3.2'
services:
  task_node:
    image: public.ecr.aws/koii-network/task_node:latest
    command: yarn initialize-start
    extra_hosts:
      - "host.docker.internal:host-gateway"

    env_file: .env.local

    container_name: task_node

    # network_mode: host
    volumes:
      - ./koii/tasks:/app/tasks # Mount the tasks folder
      - ~/.config/koii:/app/config
      - ./data:/app/data
      - ./namespace:/app/namespace
      - ./dist:/app/executables
